stripe_config: 
  N_RUs: 20 #per stripe (20)
  N_stripes: 8 #6 
  space_between_RUs: 1 #m
  space_between_stripes: 1 #m
  stripe_direction: "y"
  stripe_start_pos: [2, 2.5, 3.5] #x,y,z
  stripe_end_pos: [2, 21.5, 3.5] #x,y,z
  array_direction: 'y'

antenna_config: 
  N_antennas: 4
  pattern: 'tr38901'
  polarization: 'V'

subTHz_config:
  fc: 157.75e+9 
  bw: 3.0e+9 #6.0e+9 
  num_subcarriers: 4096 #1024
  doppler: False # todo add

objects:
  cabinet1: [1.06, 4.88, 4.19, 5.51]
  cabinet2: [1.06, 4.88, 14.23, 15.58]
  cabinet3: [1.06, 4.88, 24.27, 25.62]

sub10GHz_config:
  fc: 3.5e+9 
  bw: 20.0e+6 
  num_subcarriers: 1024 
  N_sub10GHz_antennas: 2 # per direction (V and H) => 2x2 array
  num_APs : 4 # number of APs in the scene
  pattern: 'iso'
  polarization: 'V'
  ap_pos_ceil_1: [5.25, 7.25, 3.5] # xyz
  ap_pos_ceil_2: [5.25, 18.25, 3.5] # xyz
  ap_pos_wall_1: [2, 13, 2.5] # xyz
  ap_pos_wall_2: [5.25, 23.5, 2.5] # xyz


ue_locations_config:
  num_locations: 1000
  ue_area: [1.08, 9.35, 1.88, 24.89] # Area in which to put UEs.
  safety_offset: 0.1 # Stay 10 cm away from the walls.
  z_height: 1.5 # Height at which to put the UEs.

paths:
  basepath: "./datasets_rad_pat_debug"
  scenepath: "./environments/office_space/office_space.xml"
  antenna_rad_path: "./antenna_patterns"

render_config:
  position: [6, 32, 2]
  orientation: [-1.570796, 0, 0]

random_configs:
  intermediate_renders: False # intermediatelly render the scene
  ue_orientation: 'up' #ue array is pointed upward (not used just as FYI)
  RU_orientation: 'down' #ru array is pointed downward (not used just as FYI)
  batch_size: 160 #number of RUs to process in parallel (depends on RAM/GPU memory)
