stripe_config: 
  N_RUs: 24 # Per stripe.
  N_stripes: 1
  space_between_RUs: 1 #m
  space_between_stripes: 5.13 #m
  stripe_direction: "y"
  stripe_start_pos: [11.48, 1, 10.75] #x,y,z
  stripe_end_pos: [11.48, 23.7693, 7.5]
  # Direction along which the antennas of the array are placed.
  # Developer note: The array is placed along the y-axis by default.
  array_direction: 'x'

antenna_config: 
  N_antennas: 4
  pattern: 'tr38901'
  polarization: 'V'

subTHz_config:
  fc: 157.75e+9 
  bw: 3.0e+9 #6.0e+9 
  num_subcarriers: 4096 #1024
  doppler: False # todo add

sub10GHz_config:
  fc: 3.5e+9 
  bw: 20.0e+6 
  num_subcarriers: 1024 
  N_sub10GHz_antennas: 2 # per direction (V and H) => 2x2 array
  num_APs : 4 # number of APs in the scene
  pattern: 'iso'
  polarization: 'V'
  ap_pos_ceil_1: [5.25, 7.25, 3.5] # xyz
  ap_pos_ceil_2: [5.25, 18.25, 3.5] # xyz
  ap_pos_wall_1: [2, 13, 2.5] # xyz
  ap_pos_wall_2: [5.25, 23.5, 2.5] # xyz

ue_locations_config:
  zones:
    zone1:
      bounds: [9.622, 10.522, 15.6, 17.5, 1.5, 1.5]
      steps: [0.1, 0.1, 0]
      rows: 20
      cols: 10

paths:
  basepath: "./datasets_rad_pat_debug"
  scenepath: "./environments/industry_hall_blocking/industry_hall.xml"
  antenna_rad_path: "./antenna_patterns"

# Configuration used to render the scene for debugging. These parameters are the camera position and orientation.
render_config:
  position: [9, -20, 7]
  orientation: [1.570796, 0, 0]

# A dict of objects in the scene. These are used to avoid placing UEs at these locations.
# Each defines 4 points enclosing the entire object. (x1, x2, y1, y2)
objects:
  pillar1: [1.09031, 1.35306, 25.1029, 26.2612]
  pillar2: [6.22117, 6.48392, 25.1029, 26.2612]
  pillar3: [11.3465, 11.60925, 25.1029, 26.2612]
  pillar4: [16.4904, 16.75315, 25.1029, 26.2612]
  rack1 : [2.84783, 4.77233, 16.0431, 23.6945]
  rack2 : [10.5229, 12.4474, 16.0431, 23.6945]
  rack3 : [18.2056, 20.1301, 16.0431, 23.6945]

random_configs:
  intermediate_renders: False # intermediatelly render the scene
  ue_orientation: 'up' #ue array is pointed upward (not used just as FYI)
  RU_orientation: 'down' #ru array is pointed downward (not used just as FYI)
  batch_size: 160 #number of RUs to process in parallel (depends on RAM/GPU memory)
